shops:
  - type: shopify
    id: akibapassshop
    url: https://akibapassshop.de
  - type: shopify
    id: animoon
    url: https://animoon-publishing.de
  - type: shopify
    id: leonine
    url: https://shop.leoninestudios.com
